version: '3.8'
services:
 web:
  image: padmaravi/web:robo
  container_name: web
  ports:
   - '80:80'
 mongodb:
  image: padmaravi/mongo:robo
  container_name: mongodb
  volumes:
  - mongodb: /data/db 
 catalogue:
  image: padmaravi/catalogue:robo
  container_name: catalogue
  depends_on:
   - mongodb
 redis:
  image: redis
  volumes:
  - redis: /data 
 user:
  image: padmaravi/user:robo
  container_name: user
  depends_on:
   - mongodb
   - redis
 cart:
  image: padmaravi/cart:robo
  container_name: cart
  depends_on:
   - redis
 shipping:
  image: padmaravi/shipping:robo
  container_name: shipping
  depends_on:
   - mysql
 mysql:
  image: padmaravi/mysql:robo
  container_name: mysql
  volumes: 
  - mysql: /var/lib/mysql
 rabbitmq:
  image: rabbitmq
  container_name: rabbitmq
  volumes: 
  - rabbitmq: /var/lib/rabbitmq
 payment:
  image: padmaravi/payment:robo
  container_name: payment
  depends_on:
   - rabbitmq
 ratings:
  image: padmaravi/ratings:robo
  container_name: ratings
networks:
 roboshop-network:
   driver: bridge
volumes:
 mysql: 
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/mysql
 redis: 
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/redis
 rabbitmq: 
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/rabbitmq
 mongodb: 
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/mongodb